using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ServitallersWeb.Models.Enums
{
    public enum Cities
    {
        Acacías = 1,
        Aguachica = 2,
        [Display(Name = "Agustín Codazzi")]
        AgustínCodazzi = 3,
        Apartadó = 4,
        Arauca = 5,
        Arauquita = 6,
        Arjona = 7,
        Armenia = 8,
        Baranoa = 9,
        Barbacoas = 10,
        Barbosa = 11,
        Barrancabermeja = 12,
        Barranquilla = 13,
        Bello = 14,
        Bogotá = 15,
        Bucaramanga = 16,
        Buenaventura = 17,
        Buga = 18,
        Cajicá = 19,
        Calarcá = 20,
        Caldas = 21,
        Cali = 22,
        Candelaria = 23,
        Carepa = 24,
        Cartagena = 25,
        Cartago = 26,
        Caucasia = 27,
        Cereté = 28,
        Chaparral = 29,
        Chía = 30,
        Chigorodó = 31,
        Chinchiná = 32,
        Chiquinquirá = 33,
        Ciénaga = 34,
        [Display(Name = "Ciénaga de Oro")]
        CiénagaDeOro = 35,
        Copacabana = 36,
        Corozal = 37,
        Cúcuta = 38,
        Cumaribo = 39,
        Dosquebradas = 40,
        Duitama = 41,
        [Display(Name = "El Bagre")]
        ElBagre = 42,
        [Display(Name = "El Banco")]
        ElBanco = 43,
        [Display(Name = "El Carmen de Bolívar")]
        ElCarmenDeBolívar = 44,
        [Display(Name = "El Carmen de Viboral")]
        ElCarmenDeViboral = 45,
        [Display(Name = "El Cerrito")]
        ElCerrito = 46,
        [Display(Name = "El Tambo")]
        ElTambo = 47,
        Envigado = 48,
        Espinal = 49,
        Facatativá = 50,
        Florencia = 51,
        Florida = 52,
        Floridablanca = 53,
        Fundación = 54,
        Funza = 55,
        Fusagasugá = 56,
        Galapa = 57,
        Garzón = 58,
        Girardot = 59,
        Girardota = 60,
        Girón = 61,
        Granada = 62,
        Guarne = 63,
        Ibagué = 64,
        Ipiales = 65,
        Itagüí = 66,
        Jamundí = 67,
        [Display(Name = "La Ceja")]
        LaCeja = 68,
        [Display(Name = "La Dorada")]
        LaDorada = 69,
        [Display(Name = "La Estrella")]
        LaEstrella = 70,
        [Display(Name = "La Jagua de Ibirico")]
        LaJaguaDeIbirico = 71,
        [Display(Name = "La Plata")]
        LaPlata = 72,
        Lorica = 73,
        [Display(Name = "Los Patios")]
        LosPatios = 74,
        Madrid = 75,
        Magangué = 76,
        Maicao = 77,
        Malambo = 78,
        Manaure = 79,
        Manizales = 80,
        Marinilla = 81,
        Medellín = 82,
        Mocoa = 83,
        Montelíbano = 84,
        Montería = 85,
        Mosquera = 86,
        Neiva = 87,
        Ocaña = 88,
        Palmira = 89,
        Pamplona = 90,
        Pasto = 91,
        Pereira = 92,
        Piedecuesta = 93,
        Pitalito = 94,
        [Display(Name = "Planeta Rica")]
        PlanetaRica = 95,
        Plato = 96,
        Popayán = 97,
        [Display(Name = "Puerto Asís")]
        PuertoAsís = 98,
        [Display(Name = "Puerto Colombia")]
        PuertoColombia = 99,
        Quibdó = 100,
        Riohacha = 101,
        Rionegro = 102,
        Riosucio = 103,
        Sabanalarga = 104,
        Sabaneta = 105,
        Sahagún = 106,
        [Display(Name = "San Andrés")]
        SanAndrés = 107,
        [Display(Name = "San Gil")]
        SanGil = 108,
        [Display(Name = "San José del Guaviare")]
        SanJoséDelGuaviare = 109,
        [Display(Name = "San Marcos")]
        SanMarcos = 110,
        [Display(Name = "San Onofre")]
        SanOnofre = 111,
        [Display(Name = "San Pelayo")]
        SanPelayo = 112,
        [Display(Name = "San Vicente del Caguán")]
        SanVicenteDelCaguán = 113,
        [Display(Name = "Santa Marta")]
        SantaMarta = 114,
        [Display(Name = "Santa Rosa de Cabal")]
        SantaRosaDeCabal = 115,
        [Display(Name = "Santander de Quilichao")]
        SantanderDeQuilichao = 116,
        Saravena = 117,
        Sincelejo = 118,
        Soacha = 119,
        Sogamoso = 120,
        Soledad = 121,
        Tibú = 122,
        Tierralta = 123,
        Tuchín = 124,
        Tuluá = 125,
        Tumaco = 126,
        Tunja = 127,
        Turbaco = 128,
        Turbo = 129,
        Uribia = 130,
        Valledupar = 131,
        [Display(Name = "Villa del Rosario")]
        VillaDelRosario = 132,
        Villamaría = 133,
        Villavicencio = 134,
        Yopal = 135,
        Yumbo = 136,
        Zipaquirá = 137,
        [Display(Name = "Zona Bananera")]
        ZonaBananera = 138
    }
}
